export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Precision Engineering System Palette
        primary: {
          DEFAULT: '#004ac6',
          container: '#2563eb',
          fixed: '#dbe1ff',
          'fixed-dim': '#b4c5ff',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#eeefff',
        'inverse-primary': '#b4c5ff',
        secondary: {
          DEFAULT: '#565e74',
          container: '#dae2fd',
          fixed: '#dae2fd',
          'fixed-dim': '#bec6e0',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5c647a',
        tertiary: {
          DEFAULT: '#8e3c00',
          container: '#b54e00',
          fixed: '#ffdbca',
          'fixed-dim': '#ffb690',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffece5',
        surface: {
          DEFAULT: '#f9f9ff',
          dim: '#d3daef',
          bright: '#f9f9ff',
          'container-lowest': '#ffffff',
          'container-low': '#f1f3ff',
          container: '#e9edff',
          'container-high': '#e1e8fd',
          'container-highest': '#dce2f7',
          variant: '#dce2f7',
          tint: '#0053db',
        },
        'on-surface': '#141b2b',
        'on-surface-variant': '#434655',
        'inverse-surface': '#293040',
        'inverse-on-surface': '#edf0ff',
        outline: {
          DEFAULT: '#737686',
          variant: '#c3c6d7',
        },
        // Status colors
        success: '#059669',
        'success-light': '#d1fae5',
        warning: '#d97706',
        'warning-light': '#fef3c7',
        danger: '#ba1a1a',
        'danger-light': '#ffdad6',
        info: '#2563eb',
        'info-light': '#dbeafe',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        geist: ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'container-desktop': '32px',
        'container-mobile': '16px',
        'gutter': '24px',
        'section': '64px',
        'stack-lg': '24px',
        'stack-md': '16px',
        'stack-sm': '8px',
      },
      boxShadow: {
        'level-1': '0px 4px 20px rgba(15, 23, 42, 0.05)',
        'level-2': '0px 8px 30px rgba(15, 23, 42, 0.08)',
        'level-3': '0px 20px 50px rgba(15, 23, 42, 0.15)',
        'blue-glow': '0 0 0 3px rgba(37, 99, 235, 0.15)',
        'primary-glow': '0 4px 20px rgba(37, 99, 235, 0.25)',
        'orange-glow': '0 4px 20px rgba(249, 115, 22, 0.25)',
      },
      backdropBlur: {
        xs: '4px',
        sm: '8px',
        DEFAULT: '12px',
        md: '16px',
        lg: '24px',
      },
    },
  },
  plugins: [],
}
